[server]
headless = true
port = 5000
address = "0.0.0.0"
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[ui]
hideTopBar = true
hideSidebarNav = true
